#!/bin/bash
#
# Package wxcc-agent-builder for end-user distribution.
# Creates a sanitized zip without modifying any original files.
#
# ⚠️  DEPRECATED (2026-07-10): the zip distribution is superseded by the pip
#     package `wxcc-toolkit`. Prefer:
#         pip install wxcc-toolkit && wxcc-toolkit init <folder>
#     See README.md. This script still runs but is no longer the supported path;
#     the shippable playbook now lives in src/wxcc_flow/_playbook/ (generated by
#     wxcc-dist/assemble.py).
#
# Usage: ./package-for-distribution.sh [output-name]
#   output-name: optional zip filename (default: wxcc-agent-builder)

set -euo pipefail

echo "⚠️  DEPRECATED: this zip packager is superseded by 'pip install wxcc-toolkit' → 'wxcc-toolkit init <folder>'." >&2
echo "    It still runs, but the pip package is now the supported distribution. See README.md." >&2

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
OUTPUT_NAME="${1:-wxcc-agent-builder}"
STAGING_DIR=$(mktemp -d)
DIST_DIR="${STAGING_DIR}/${OUTPUT_NAME}"

cleanup() {
    rm -rf "${STAGING_DIR}"
}
trap cleanup EXIT

echo "=== Packaging wxcc-agent-builder for distribution ==="
echo "Staging in: ${STAGING_DIR}"

mkdir -p "${DIST_DIR}"

# --- Copy essential files ---

# Top-level
cp "${SCRIPT_DIR}/CLAUDE.md" "${DIST_DIR}/"
cp "${SCRIPT_DIR}/.gitignore" "${DIST_DIR}/"

# .claude/agents
mkdir -p "${DIST_DIR}/.claude/agents"
cp "${SCRIPT_DIR}/.claude/agents/wxcc-agent-builder.md" "${DIST_DIR}/.claude/agents/"

# .claude/skills (all skills, SKILL.md + reference.md only)
for skill_dir in "${SCRIPT_DIR}/.claude/skills"/*/; do
    skill_name=$(basename "${skill_dir}")
    mkdir -p "${DIST_DIR}/.claude/skills/${skill_name}"
    for f in SKILL.md reference.md; do
        if [ -f "${skill_dir}${f}" ]; then
            cp "${skill_dir}${f}" "${DIST_DIR}/.claude/skills/${skill_name}/"
        fi
    done
done

# .claude/rules (doc-lookup enforcement rules — platform accuracy guardrails)
mkdir -p "${DIST_DIR}/.claude/rules"
cp "${SCRIPT_DIR}"/.claude/rules/*.md "${DIST_DIR}/.claude/rules/"

# docs/reference
mkdir -p "${DIST_DIR}/docs/reference"
cp "${SCRIPT_DIR}"/docs/reference/*.md "${DIST_DIR}/docs/reference/"

# docs/reference/flow-designer-activities (situational activity docs — one file per activity)
mkdir -p "${DIST_DIR}/docs/reference/flow-designer-activities"
cp "${SCRIPT_DIR}"/docs/reference/flow-designer-activities/*.md "${DIST_DIR}/docs/reference/flow-designer-activities/"

# docs/templates
mkdir -p "${DIST_DIR}/docs/templates"
cp "${SCRIPT_DIR}"/docs/templates/*.md "${DIST_DIR}/docs/templates/"
# JSON templates (e.g. ai-agent-studio-import-template.json) if any exist
if ls "${SCRIPT_DIR}"/docs/templates/*.json 1>/dev/null 2>&1; then
    cp "${SCRIPT_DIR}"/docs/templates/*.json "${DIST_DIR}/docs/templates/"
fi

# docs/playbooks
mkdir -p "${DIST_DIR}/docs/playbooks"
cp "${SCRIPT_DIR}"/docs/playbooks/*.md "${DIST_DIR}/docs/playbooks/"

# docs/examples (if any .md files exist)
mkdir -p "${DIST_DIR}/docs/examples"
if ls "${SCRIPT_DIR}"/docs/examples/*.md 1>/dev/null 2>&1; then
    cp "${SCRIPT_DIR}"/docs/examples/*.md "${DIST_DIR}/docs/examples/"
fi

# docs/plans — empty dir with .gitkeep (user's builds go here)
mkdir -p "${DIST_DIR}/docs/plans"
touch "${DIST_DIR}/docs/plans/.gitkeep"

# --- Create sanitized .mcp.json ---

cat > "${DIST_DIR}/.mcp.json" << 'MCPEOF'
{
  "mcpServers": {
    "supabase": {
      "command": "npx",
      "args": [
        "-y",
        "@supabase/mcp-server-supabase@latest",
        "--project-ref",
        "YOUR_SUPABASE_PROJECT_REF"
      ],
      "env": {
        "SUPABASE_ACCESS_TOKEN": "YOUR_SUPABASE_ACCESS_TOKEN"
      }
    },
    "wxcc-flow-builder": {
      "type": "http",
      "url": "https://flow-store.produs1.ciscoccservice.com/flow-store/mcp",
      "headers": {
        "Authorization": "Bearer YOUR_FLOW_STORE_TOKEN"
      }
    }
  }
}
MCPEOF

# --- Create settings.json with pre-approved permissions ---

mkdir -p "${DIST_DIR}/.claude"
cat > "${DIST_DIR}/.claude/settings.json" << 'SETTINGSEOF'
{
  "permissions": {
    "allow": [
      "Skill(design-flow)",
      "Skill(build-flow-designer)",
      "Skill(build-flow-programmatic)",
      "Skill(build-spec-diagram)",
      "Skill(build-action)",
      "Skill(configure-ai-agent)",
      "Skill(design-scripted-agent)",
      "Skill(configure-scripted-agent)",
      "Skill(build-scripted-fulfillment)",
      "Skill(build-digital-inbound)",
      "Skill(build-outbound-flow)",
      "Skill(build-notification)",
      "Skill(build-solution-docs)",
      "Skill(wxcc-debug)",

      "mcp__supabase__list_tables",
      "mcp__supabase__execute_sql",
      "mcp__supabase__get_publishable_keys",
      "mcp__supabase__get_project_url",
      "mcp__supabase__apply_migration",
      "mcp__supabase__list_migrations",
      "mcp__supabase__list_extensions",
      "mcp__supabase__get_logs",
      "mcp__supabase__search_docs",

      "mcp__wxcc-flow-builder__list_flows",
      "mcp__wxcc-flow-builder__get_flow",
      "mcp__wxcc-flow-builder__create_flow",
      "mcp__wxcc-flow-builder__save_flow_draft",
      "mcp__wxcc-flow-builder__patch_flow_draft",
      "mcp__wxcc-flow-builder__validate_flow",
      "mcp__wxcc-flow-builder__get_flow_template",
      "mcp__wxcc-flow-builder__get_activity_definitions",
      "mcp__wxcc-flow-builder__get_activity_node_schema",
      "mcp__wxcc-flow-builder__describe_activity",
      "mcp__wxcc-flow-builder__get_choices",
      "mcp__wxcc-flow-builder__list_event_specifications"
    ]
  },
  "enabledMcpjsonServers": [
    "supabase",
    "wxcc-flow-builder"
  ]
}
SETTINGSEOF

# --- Create setup README ---

cat > "${DIST_DIR}/SETUP.md" << 'SETUPEOF'
# Setup

## Prerequisites

- [Claude Code CLI](https://docs.anthropic.com/en/docs/claude-code) installed
- A Webex Contact Center environment with:
  - Webex Connect tenant (for building flows)
  - AI Agent Studio access (for configuring the AI agent)
  - Control Hub admin access (for WxCC routing)

## 1. Configure your MCP servers

Edit `.mcp.json` and replace the placeholder values:

### Supabase (if using Supabase as your database)
- `YOUR_SUPABASE_PROJECT_REF` — your Supabase project reference ID (from Project Settings > General)
- `YOUR_SUPABASE_ACCESS_TOKEN` — generate at https://supabase.com/dashboard/account/tokens

### Flow Store (WxCC Flow Designer — `wxcc-flow-builder` MCP)
- `YOUR_FLOW_STORE_TOKEN` — a Webex access token valid for your WxCC org. Generate a
  personal access token at https://developer.webex.com (Getting Started → copy your token).
  The MCP endpoint is `https://flow-store.produs1.ciscoccservice.com/flow-store/mcp`.
  Note: developer-portal tokens expire after ~12 hours; refresh and update `.mcp.json` when
  the server returns a 401.

If you don't use one of these backends, remove its entry from `.mcp.json`.

## 2. Start building

```bash
claude
```

Then type: `/wxcc-agent-builder`

The builder will walk you through everything — from database setup through a working AI agent handling calls.

## 3. Debugging

If an action isn't working, type: `/wxcc-debug`
SETUPEOF

# --- Build the zip ---

OUTPUT_PATH="${SCRIPT_DIR}/${OUTPUT_NAME}.zip"
rm -f "${OUTPUT_PATH}"

(cd "${STAGING_DIR}" && zip -r "${OUTPUT_PATH}" "${OUTPUT_NAME}" -x "*/.DS_Store" "*/.*swp")

echo ""
echo "=== Done ==="
echo "Output: ${OUTPUT_PATH}"
echo "Size:   $(du -h "${OUTPUT_PATH}" | cut -f1)"
echo ""
echo "Contents:"
(cd "${STAGING_DIR}" && find "${OUTPUT_NAME}" -type f | sort)
