# GENERATED by tools/generator — do not edit. Regenerate instead.
"""Generated `wxcc-flow api widgets` commands (Flow Store API)."""
import json
import typer
from wxcc_flow.client import FlowClient, FlowStoreError
from wxcc_flow.output import print_json, print_table

app = typer.Typer(help="Flow Store widgets operations (generated).", no_args_is_help=True)


@app.command("list")
def cmd_list(
    kind: str = typer.Option(None, "--kind", help="Choices: A, B"),
    page: int = typer.Option(None, "--page", help="Fetch a single 0-based page. Omit to fetch all pages."),
    size: int = typer.Option(None, "--size", help="Page size (default 100 when fetching all)."),
    output: str = typer.Option("table", "-o", "--output", help="Output format: table|json"),
    debug: bool = typer.Option(False, "--debug"),
):
    """List widgets. [operationId: findWidgets]"""
    c = FlowClient(debug=debug)
    params = {}
    if kind is not None:
        params["kind"] = kind
    _path = f"/{c.org_id}/project/{c.project_id}/widgets"
    try:
        if page is not None:
            params["page"] = page
            if size is not None:
                params["size"] = size
            data = c.get(_path, params=params)
            items = data if isinstance(data, list) else data.get("widgets", data.get("items", data.get("data", [])))
        else:
            _size = size if size is not None else 100
            items = []
            _page = 0
            while True:
                _p = dict(params)
                _p["page"] = _page
                _p["size"] = _size
                data = c.get(_path, params=_p)
                batch = data if isinstance(data, list) else data.get("widgets", data.get("items", data.get("data", [])))
                items.extend(batch)
                if len(batch) < _size:
                    break
                _page += 1
                if _page > 100000:
                    break
    except FlowStoreError as e:
        typer.echo(f"Error {e.status_code}: {e.body}", err=True)
        raise typer.Exit(1)
    if output == "table":
        print_table(items, columns=[('ID', 'id'), ('Name', 'name')], limit=0)
    else:
        print_json(items)


@app.command("create")
def create(
    name: str = typer.Option(None, "--name", help=""),
    count: int = typer.Option(None, "--count", help=""),
    json_body: str = typer.Option(None, "--json-body", help="Full JSON body (overrides flags)"),
    output: str = typer.Option("json", "-o", "--output", help="Output format: json"),
    debug: bool = typer.Option(False, "--debug"),
):
    """Create a widget. [operationId: createWidget]\n\nExample --json-body:\n  '{\"name\":\"...\",\"count\":0,\"spec\":{}}'"""
    c = FlowClient(debug=debug)
    params = {}
    if json_body is not None:
        body = json.loads(json_body)
    else:
        body = {}
        if name is not None:
            body["name"] = name
        if count is not None:
            body["count"] = count
    _missing = [k for k in ['name'] if k not in body or body[k] is None]
    if _missing:
        typer.echo("Error: Missing required fields: " + ", ".join(_missing), err=True)
        raise typer.Exit(1)
    _path = f"/{c.org_id}/project/{c.project_id}/widgets"
    try:
        data = c.post(_path, json_body=body, params=params)
    except FlowStoreError as e:
        typer.echo(f"Error {e.status_code}: {e.body}", err=True)
        raise typer.Exit(1)
    print_json(data)


@app.command("get")
def get(
    widget_id: str = typer.Argument(..., help="widgetId"),
    output: str = typer.Option("json", "-o", "--output", help="Output format: json"),
    debug: bool = typer.Option(False, "--debug"),
):
    """Get a widget. [operationId: getWidget]"""
    c = FlowClient(debug=debug)
    params = {}
    _path = f"/{c.org_id}/project/{c.project_id}/widgets/{widget_id}"
    try:
        data = c.get(_path, params=params)
    except FlowStoreError as e:
        typer.echo(f"Error {e.status_code}: {e.body}", err=True)
        raise typer.Exit(1)
    print_json(data)


@app.command("merge-patch")
def merge_patch(
    debug: bool = typer.Option(False, "--debug"),
):
    """[BLOCKED] no-op; use update [operationId: mergeWidget]"""
    typer.echo("no-op; use update", err=True)
    raise typer.Exit(2)


@app.command("delete")
def delete(
    widget_id: str = typer.Argument(..., help="widgetId"),
    server_force: str = typer.Option(None, "--server-force", help=""),
    force: bool = typer.Option(False, "--force", help="Skip the confirmation prompt"),
    output: str = typer.Option("json", "-o", "--output", help="Output format: json"),
    debug: bool = typer.Option(False, "--debug"),
):
    """Delete a widget. [operationId: deleteWidget]"""
    if not force:
        typer.confirm(f"Delete {widget_id}?", abort=True)
    c = FlowClient(debug=debug)
    params = {}
    if server_force is not None:
        params["force"] = server_force
    _path = f"/{c.org_id}/project/{c.project_id}/widgets/{widget_id}"
    try:
        data = c.delete(_path, params=params)
    except FlowStoreError as e:
        typer.echo(f"Error {e.status_code}: {e.body}", err=True)
        raise typer.Exit(1)
    print_json(data)


@app.command("import")
def cmd_import(
    file: str = typer.Argument(..., help="Path to the JSON file to upload"),
    flow_type: str = typer.Option(None, "--flow-type", help=""),
    overwrite: str = typer.Option(None, "--overwrite", help=""),
    output: str = typer.Option("json", "-o", "--output", help="Output format: json"),
    debug: bool = typer.Option(False, "--debug"),
):
    """Import a widget. [operationId: importWidget]"""
    c = FlowClient(debug=debug)
    params = {}
    if flow_type is not None:
        params["Flow Type"] = flow_type
    if overwrite is not None:
        params["overwrite"] = overwrite
    _path = f"/{c.org_id}/project/{c.project_id}/widgets:import"
    with open(file, "rb") as _fh:
        _content = _fh.read()
    import os as _os
    try:
        data = c.post_multipart(_path, _os.path.basename(file), _content, params=params)
    except FlowStoreError as e:
        typer.echo(f"Error {e.status_code}: {e.body}", err=True)
        raise typer.Exit(1)
    print_json(data)


@app.command("refresh")
def refresh(
    output: str = typer.Option("json", "-o", "--output", help="Output format: json"),
    debug: bool = typer.Option(False, "--debug"),
):
    """Refresh widgets. [operationId: refreshWidgets]"""
    typer.echo("Warning: may be slow on big orgs", err=True)
    c = FlowClient(debug=debug)
    params = {}
    _path = f"/{c.org_id}/project/{c.project_id}/widgets:refresh"
    try:
        data = c.post(_path, params=params)
    except FlowStoreError as e:
        typer.echo(f"Error {e.status_code}: {e.body}", err=True)
        raise typer.Exit(1)
    print_json(data)
